---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre"

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - six
    - psutil
    - pywinrm
  exclude:
    python:
      - docker
    system:
      - python3-Cython

additional_build_files:
  - src: ./configs/custom_entrypoint
    dest: scripts
  - src: ./configs/ansible.cfg
    dest: configs

images:
  base_image:
    name: registry.fedoraproject.org/fedora:38

additional_build_steps:
  prepend_base:
    - COPY _build/scripts/custom_entrypoint /opt/builder/bin/custom_entrypoint
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final:
    - RUN chmod +x /opt/builder/bin/custom_entrypoint
options:
  container_init:
    entrypoint: '["/opt/builder/bin/custom_entrypoint"]'
  skip_ansible_check: true
